/*!
 * @file     core_common.c
 * @brief    Strings for core error codes.
 *
 * @copyright Copyright (C) 2019 Siemens Aktiengesellschaft.\n
 *            All rights reserved.
 */

#include "core_common.h"

const char *mcl_core_return_code_strings[MCL_CORE_RETURN_CODE_END] =
{
    "MCL_OK",
    "MCL_FAIL",
    "MCL_TRIGGERED_WITH_NULL",
    "MCL_OUT_OF_MEMORY",
    "MCL_INVALID_PARAMETER",
    "MCL_INVALID_LOG_LEVEL",
    "MCL_NO_SERVER_TIME",
    "MCL_NO_ACCESS_TOKEN_EXISTS",
    "MCL_NO_ACCESS_TOKEN_PROVIDED",
    "MCL_NO_FILE_SUPPORT",
    "MCL_OPERATION_IS_NOT_SUPPORTED",
    "MCL_COULD_NOT_RESOLVE_PROXY",
    "MCL_COULD_NOT_RESOLVE_HOST",
    "MCL_COULD_NOT_CONNECT",
    "MCL_SSL_HANDSHAKE_FAIL",
    "MCL_NETWORK_SEND_FAIL",
    "MCL_NETWORK_RECEIVE_FAIL",
    "MCL_SERVER_CERTIFICATE_NOT_VERIFIED",
    "MCL_IMPROPER_CERTIFICATE",
    "MCL_REQUEST_TIMEOUT",
    "MCL_SERVER_FAIL",
    "MCL_CREATED",
    "MCL_PARTIAL_CONTENT",
    "MCL_BAD_REQUEST",
    "MCL_UNAUTHORIZED",
    "MCL_FORBIDDEN",
    "MCL_NOT_FOUND",
    "MCL_CONFLICT",
    "MCL_PRECONDITION_FAIL",
    "MCL_REQUEST_PAYLOAD_TOO_LARGE",
    "MCL_TOO_MANY_REQUESTS",
    "MCL_UNEXPECTED_RESULT_CODE",
    "MCL_NOT_ONBOARDED",
    "MCL_ALREADY_ONBOARDED",
    "MCL_EXCHANGE_STREAMING_IS_ACTIVE",
    "MCL_CREDENTIALS_UP_TO_DATE",
    "MCL_CANNOT_ENTER_CRITICAL_SECTION",
    "MCL_BAD_CONTENT_ENCODING",
    "MCL_JSON_NON_EXISTING_CHILD",
    "MCL_JSON_NAME_DUPLICATION",
    "MCL_JSON_TYPE_MISMATCH",
    "MCL_SHA256_CALCULATION_FAIL",
    "MCL_CREDENTIALS_NOT_SAVED",
    "MCL_CREDENTIALS_NOT_LOADED",
    "MCL_LIST_IS_EMPTY",
    "MCL_LIMIT_EXCEEDED"
};
